### ISSUE TITLE
SPI problem, esp32, basic receiver demo

### ISSUE THREAD

**Issue by habub** [nopnop2002/esp-idf-cc1101#3]
Hello,

Although I think I set up everything according to the readme (with menuconfig), I don't receive any signals.
In the terminal log it looks like the CS pin is not defined ocrrectly:
GPIO[5]| **InputEn: 0| OutputEn: 0**| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0

This is the terminal log. Do you see other issues?

W (349) MAIN: Set frequency to 433MHz
W (349) MAIN: Set speed to 4800bps
I (359) gpio: GPIO[5]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (369) CC1101: spi_bus_initialize=0
I (369) CC1101: spi_bus_add_device=0
I (369) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2
I (389) CC1101: CC1101_PARTNUM 0
I (389) CC1101: CC1101_VERSION 20
W (389) MAIN: Set channel to 0
I (399) rx_task: Start
I (399) main_task: Returned from app_main()

Thanks

**Comment by nopnop2002** [comment]
There is no such code in the sample I am providing.
```
I (399) main_task: Returned from app_main()
```

Perhaps you have made some changes.

**Comment by habub** [comment]
Thanks.
I started from scratch, after deleting the project folder and erasing the flash. It's still the same result....
I don't understand where this is coming from.

**Comment by nopnop2002** [comment]
Works with esp-idf v5.1.

I used the default gpio.

![cc1101](https://github.com/nopnop2002/esp-idf-cc1101/assets/6020549/4b275f10-b458-4145-9a8f-5b8915fe3883)

**Comment by habub** [comment]
1) First of all, I see you also have exactly the same log as I do.....
![nop@nop](https://github.com/nopnop2002/esp-idf-cc1101/assets/8079997/b79d0a20-df69-4051-9f95-2cb526458c6c)

2) Does the code receive only specific protocol? I have general 433MHz transmitter, not another ESP32. Do I need a specific transmitter protocol? Or can it work with any signal?

**Comment by nopnop2002** [comment]
>Does the receiver work only with specific protocol? 

Yes.
It work only CC1101.
