### ISSUE TITLE
cc1101 register settings

### ISSUE THREAD

**Issue by habub** [nopnop2002/esp-idf-cc1101#4]
Hello,

1) I think your register settings, at least for 433MHz band, are not correct. I checked in several other repos, for example: https://github.com/SpaceTeddy/CC1101/issues/33#issuecomment-733766014
After updating the relevant registers (at least FREQ2_433, FREQ1_433, FREQ0_433) I started receiving signals...

2) After updating these registers I now get endless messages. Non stop. Looks like something is blocking the radio signal, or the settings is still not correct. You can see the LQI, RSSI and Length values are constant.
Are you familiar with this type of problem?
....
W (389) MAIN: Set channel to 0
I (399) rx_task: Start Rx
I (409) main_task: Returned from app_main()
I (409) rx_task: Received packet...
I (409) rx_task: packet.lqi: -64
I (409) rx_task: packet.rssi: -74dBm
I (419) rx_task: packet.length: 255
I (439) rx_task: Received packet...
I (439) rx_task: packet.lqi: -64
I (439) rx_task: packet.rssi: -74dBm
I (439) rx_task: packet.length: 255
I (459) rx_task: Received packet...
I (459) rx_task: packet.lqi: -64
I (459) rx_task: packet.rssi: -74dBm
I (459) rx_task: packet.length: 255
I (479) rx_task: Received packet...
I (479) rx_task: packet.lqi: -64
I (479) rx_task: packet.rssi: -74dBm
I (479) rx_task: packet.length: 255
I (499) rx_task: Received packet...
I (499) rx_task: packet.lqi: -64
I (499) rx_task: packet.rssi: -74dBm
I (499) rx_task: packet.length: 255
I (519) rx_task: Received packet...
I (519) rx_task: packet.lqi: -64
I (519) rx_task: packet.rssi: -74dBm
I (519) rx_task: packet.length: 255
I (539) rx_task: Received packet...
I (539) rx_task: packet.lqi: -64
I (539) rx_task: packet.rssi: -74dBm
I (539) rx_task: packet.length: 255
I (559) rx_task: Received packet...
I (559) rx_task: packet.lqi: -64
I (559) rx_task: packet.rssi: -74dBm
I (559) rx_task: packet.length: 255
I (579) rx_task: Received packet...
I (579) rx_task: packet.lqi: -64
I (579) rx_task: packet.rssi: -74dBm
I (579) rx_task: packet.length: 255
I (599) rx_task: Received packet...
I (599) rx_task: packet.lqi: -64
I (599) rx_task: packet.rssi: -74dBm
I (599) rx_task: packet.length: 255
I (619) rx_task: Received packet...
.........endless

**Comment by nopnop2002** [comment]
To set up a system with channel numbers, the desired __channel spacing__ is programmed with the MDMCFG0.CHANSPC_M and MDMCFG1.CHANSPC_E registers. 

The channel spacing registers are mantissa and exponent respectively. 

The base or start frequency is set by the 24 bit frequency word located in the FREQ2, FREQ1, and FREQ0 registers. 

This word will typically be set to the centre of the lowest channel frequency that is to be used.

The desired channel number is programmed with the 8-bit channel number register, CHANNR.CHAN, which is multiplied by the channel offset. 


I think it's a meaningless register if only channel 0 is used.

**Comment by nopnop2002** [comment]
To set up a system with channel numbers, the desired __channel spacing__ is programmed with the MDMCFG0.CHANSPC_M and MDMCFG1.CHANSPC_E registers. 

The channel spacing registers are mantissa and exponent respectively. 

The base or start frequency is set by the 24 bit frequency word located in the FREQ2, FREQ1, and FREQ0 registers. 

This word will typically be set to the centre of the lowest channel frequency that is to be used.

The desired channel number is programmed with the 8-bit channel number register, CHANNR.CHAN, which is multiplied by the channel offset. 


When changing FREQ2, FREQ1, and FREQ0 registers, change MDMCFG0.CHANSPC_M and MDMCFG1.CHANSPC_E registers at the same time.

The formula is given in the datasheet.
